In [1]:
import tensorflow as tf
print(tf.__version__)

2022-06-01 09:13:12.230682: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-06-01 09:13:12.349292: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-01 09:13:12.349317: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


2.9.0


In [2]:
##
## Model sieci
##

inputs = tf.keras.Input(shape=(2,), name='i')
# https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense
dense = tf.keras.layers.Dense(3, activation='relu', input_shape=(2,), name='d')(inputs)
outputs = tf.keras.layers.Dense(1, activation='relu', input_shape=(3,), name='o')(dense)

model = tf.keras.Model(inputs=inputs, outputs=outputs, name='XOR')

2022-06-01 09:13:39.665435: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-06-01 09:13:39.665477: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-01 09:13:39.665507: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (project-3699c8b4-73dd-490e-9323-5482549ab7cb): /proc/driver/nvidia/version does not exist
2022-06-01 09:13:39.666300: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
##
## Trening sieci
##

(x_train, y_train) = ([[0, 0], [1, 0], [0, 1], [1, 1]], [[0], [1], [1], [0]])
(x_test, y_test) = ([[0, 0], [1, 0], [0, 1], [1, 1]], [[0], [1], [1], [0]])

model.compile(loss='MSE', optimizer=tf.keras.optimizers.Adam(), metrics=['accuracy'])
model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10


1/1 [==============================] - ETA: 0s - loss: 0.4453 - accuracy: 0.5000

1/1 [==============================] - 1s 1s/step - loss: 0.4453 - accuracy: 0.5000


Epoch 2/10


1/1 [==============================] - ETA: 0s - loss: 0.4435 - accuracy: 0.5000

1/1 [==============================] - 0s 5ms/step - loss: 0.4435 - accuracy: 0.5000


Epoch 3/10


1/1 [==============================] - ETA: 0s - loss: 0.4416 - accuracy: 0.5000

1/1 [==============================] - 0s 4ms/step - loss: 0.4416 - accuracy: 0.5000


Epoch 4/10


1/1 [==============================] - ETA: 0s - loss: 0.4397 - accuracy: 0.5000

1/1 [==============================] - 0s 4ms/step - loss: 0.4397 - accuracy: 0.5000


Epoch 5/10


1/1 [==============================] - ETA: 0s - loss: 0.4379 - accuracy: 0.5000

1/1 [==============================] - 0s 5ms/step - loss: 0.4379 - accuracy: 0.5000


Epoch 6/10


1/1 [==============================] - ETA: 0s - loss: 0.4360 - accuracy: 0.5000

1/1 [==============================] - 0s 88ms/step - loss: 0.4360 - accuracy: 0.5000


Epoch 7/10


1/1 [==============================] - ETA: 0s - loss: 0.4342 - accuracy: 0.5000

1/1 [==============================] - 0s 5ms/step - loss: 0.4342 - accuracy: 0.5000


Epoch 8/10


1/1 [==============================] - ETA: 0s - loss: 0.4321 - accuracy: 0.5000

1/1 [==============================] - 0s 6ms/step - loss: 0.4321 - accuracy: 0.5000


Epoch 9/10


1/1 [==============================] - ETA: 0s - loss: 0.4297 - accuracy: 0.5000

1/1 [==============================] - 0s 9ms/step - loss: 0.4297 - accuracy: 0.5000


Epoch 10/10


1/1 [==============================] - ETA: 0s - loss: 0.4273 - accuracy: 0.5000

1/1 [==============================] - 0s 5ms/step - loss: 0.4273 - accuracy: 0.5000


In [4]:
print(model.get_weights())

[array([[-0.6201489 , -0.15263873,  0.46320987],
       [ 0.37627277,  0.8653522 , -0.95397925]], dtype=float32), array([ 0.00998061, -0.00996671, -0.00190666], dtype=float32), array([[ 0.82235587],
       [-0.19739369],
       [-0.0120742 ]], dtype=float32), array([0.01001761], dtype=float32)]


In [5]:
model.predict(x_train)

1/1 [==============================] - ETA: 0s

1/1 [==============================] - 0s 275ms/step


array([[0.01822522],
       [0.00444775],
       [0.15880767],
       [0.        ]], dtype=float32)

In [6]:
model.fit(x_train, y_train, epochs=1000, verbose=0)

In [124]:
model.evaluate(x_train, y_train)

1/1 [==============================] - ETA: 0s - loss: 0.0046 - accuracy: 1.0000

1/1 [==============================] - 0s 89ms/step - loss: 0.0046 - accuracy: 1.0000


[0.004623829387128353, 1.0]

In [125]:
model.predict(x_train)

array([[0.07934888],
       [0.923924  ],
       [0.94797313],
       [0.06086645]], dtype=float32)

In [126]:
x_train

[[0, 0], [1, 0], [0, 1], [1, 1]]

In [127]:
model.get_weights()

[array([[ 1.1014094 , -0.39685658, -1.3882769 ],
        [ 0.5182193 ,  1.6308154 ,  1.3883033 ]], dtype=float32),
 array([2.2704300e-01, 3.9688876e-01, 8.8740271e-05], dtype=float32),
 array([[ 0.5170005 ],
        [-0.69359213],
        [ 1.2474403 ]], dtype=float32),
 array([0.23713577], dtype=float32)]

In [64]:
0.23*-0.47 + 0.81*1.25-1.23*0.76

-0.03039999999999976